default:
  image: registry.znuny.com/docker/zammad-ruby:2.6.5

include:
  - local: '/.gitlab/ci/base.yml'
  - local: '/.gitlab/ci/pre.yml'
  - local: '/.gitlab/ci/integration.yml'
  - local: '/.gitlab/ci/rspec.yml'
  - local: '/.gitlab/ci/unit.yml'
  - local: '/.gitlab/ci/browser-core.yml'
  - local: '/.gitlab/ci/browser-integration.yml'

# Stages
stages:
  - pre
  - test
  - browser-core
  - browser-integration

# Global variables added to the ENV of each job
variables:
  # for faster translation loading
  Z_LOCALES: "en-us:de-de"
  # Browser tests and variables
  RAILS_SERVE_STATIC_FILES: "true"
  REMOTE_URL: "http://selenium:24444/wd/hub"
  TZ: "Europe/London"
  # docker elgalu/selenium variables for parallel browser instance creation
  MAX_INSTANCES: "50"
  MAX_SESSIONS: "50"
  # docker-imap-devel variables required for browser tests
  MAILNAME: "mail.test.dc.zammad.com"
  MAILBOX_INIT: "zammad@mail.test.dc.zammad.com:zammad"
  MAIL_ADDRESS: "zammad@mail.test.dc.zammad.com"
  MAIL_PASS: "zammad"

# Cache gems in between jobs and pipelines
# ATTENTION: We use a combination of the Ruby major and minor version number
# as a key for the cache to avoid cache growth and incompatibilities between
# the gems. Search hook: 2.6.5 (change it when updating the Ruby version too)
cache:
  key: "ruby26"
  paths:
    - vendor/ruby

# Initialize application env
before_script:
  - bundle install -j $(nproc) --path vendor
  - bundle exec ruby script/build/database_config.rb

